### ISSUE TITLE
inference.py error ....

### ISSUE THREAD

**Issue by choikhss** [ybkscht/EfficientPose#14]
Currently I am running INFERENCE.PY.
I get an error like the one below.
Can you tell what the problem is?

Error 

Relying on driver to perform ptx compilation. This message will be only logged once.
2021-04-06 10:43:28.641402: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
  0%|          | 0/1188 [28:43<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/pycharm-community-2020.3.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/pycharm-community-2020.3.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/PycharmProjects/EfficientPose/EfficientPose/inference.py", line 313, in <module>
    main()
  File "/home/user/PycharmProjects/EfficientPose/EfficientPose/inference.py", line 103, in main
    draw_name = draw_name)
  File "/home/user/PycharmProjects/EfficientPose/EfficientPose/utils/visualization.py", line 166, in draw_detections
    points_bbox_2D = project_bbox_3D_to_2D(class_to_bbox_3D[labels[i]], rotations[i, :], translation_vector, camera_matrix, append_centerpoint = True)
KeyError: 0
python-BaseException

Process finished with exit code 1

Thank you

**Comment by ybkscht** [comment]
Hi choikhss,

It sounds like there is a problem with the class_to_bbox_3D dictionary (empty?). 
This dict is used to map the object class label to the corresponding numpy array containing the object's 3D bounding box.
It is created early in the main function of inference.py in this line: 
`class_to_3d_bboxes = {class_idx: name_to_3d_bboxes[name] for class_idx, name in class_to_name.items()}`
If you use a custom dataset you have to modify this dict (also class_to_name and camera_matrix) to provide the needed informations about the objects you use.

Sincerely,
Yannick

**Comment by choikhss** [comment]
Thanks for your comment!

class_to_bbox_3D dictionary is not empty ..
I am currently using linemod and class_to_name is {8: "driller"}.
I am not using a custom data. 
And I have only modified path_to_images, path_to_weights, save_path and class_to_name in inference.py.

Thank you

**Comment by choikhss** [comment]
I solved!!!! Thank you!
