### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hans24o** [ybkscht/EfficientPose#28]
I set up the repositoy as instructed (`new environment` -> ` Tensorflow 1.15.0` -> `requirements.txt` -> `setup.py`) and even downgraded my numpy version to 1.18.5. This seems to work successfully. 

I still can't run the `inference_webcam.py` tough and receive the following output:
```2021-06-01 08:37:52.175171: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From inference_webcam.py:124: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From inference_webcam.py:126: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-06-01 08:37:54.436702: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2021-06-01 08:37:54.438865: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-06-01 08:37:54.464910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 760 major: 3 minor: 0 memoryClockRate(GHz): 1.0715
pciBusID: 0000:01:00.0
2021-06-01 08:37:54.465119: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-06-01 08:37:54.470950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-06-01 08:37:54.474237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-06-01 08:37:54.475836: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-06-01 08:37:54.480456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-06-01 08:37:54.483631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-06-01 08:37:54.492904: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-01 08:37:54.494293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-06-01 08:37:55.110580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-01 08:37:55.110727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2021-06-01 08:37:55.112652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2021-06-01 08:37:55.113550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1396 MB memory) -> physical GPU (device: 0, name: GeForce GTX 760, pci bus id: 0000:01:00.0, compute capability: 3.0)

Building model...

WARNING:tensorflow:From D:\Users\<User>\anaconda3\envs\EfficientPose2\lib\site-packages\tensorflow_core\python\util\deprecation.py:507: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
WARNING:tensorflow:From D:\Users\<User>\anaconda3\envs\EfficientPose2\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2021-06-01 08:38:11.434139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 760 major: 3 minor: 0 memoryClockRate(GHz): 1.0715
pciBusID: 0000:01:00.0
2021-06-01 08:38:11.434319: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-06-01 08:38:11.436316: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-06-01 08:38:11.436992: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-06-01 08:38:11.437411: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-06-01 08:38:11.437870: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-06-01 08:38:11.438298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-06-01 08:38:11.438745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-01 08:38:11.439238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-06-01 08:38:11.440169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 760 major: 3 minor: 0 memoryClockRate(GHz): 1.0715
pciBusID: 0000:01:00.0
2021-06-01 08:38:11.440266: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-06-01 08:38:11.440673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-06-01 08:38:11.441075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-06-01 08:38:11.441503: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-06-01 08:38:11.441936: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-06-01 08:38:11.442460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-06-01 08:38:11.442859: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-06-01 08:38:11.443290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-06-01 08:38:11.443651: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-01 08:38:11.443984: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2021-06-01 08:38:11.444343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2021-06-01 08:38:11.444790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1396 MB memory) -> physical GPU (device: 0, name: GeForce GTX 760, pci bus id: 0000:01:00.0, compute capability: 3.0)
WARNING:tensorflow:From C:\Users\<User>\Documents\GitHub\EfficientPose\layers.py:298: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Done!

Loading weights...
Traceback (most recent call last):
  File "inference_webcam.py", line 317, in <module>
    main()
  File "inference_webcam.py", line 66, in main
    model, image_size = build_model_and_load_weights(phi, num_classes, score_threshold, path_to_weights)
  File "inference_webcam.py", line 221, in build_model_and_load_weights
    efficientpose_prediction.load_weights(path_to_weights, by_name=True)
  File "D:\Users\<User>\anaconda3\envs\EfficientPose2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "D:\Users\<User>\anaconda3\envs\EfficientPose2\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "D:\Users\<User>\anaconda3\envs\EfficientPose2\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 712, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

Has someone experienced this issue and solved it?

**Comment by ybkscht** [comment]
Hi @hans24o ,

nikonnext apparently had the same issue [here](https://github.com/ybkscht/EfficientPose/issues/27#issuecomment-851894659) and solved it with downgrading h5py. I hope this helps.

Sincerely,
Yannick

**Comment by finnweiler** [comment]
This fixed it for me. Thank you very much!
